export type Database = {
  public: {
    Tables: {
      user_profiles: {
        Row: {
          id: string
          employee_id: string
          email: string
          secondary_email?: string
          first_name: string
          middle_name?: string
          last_name: string
          preferred_name?: string
          display_name?: string
          phone?: string
          mobile_phone?: string
          date_of_birth?: string
          gender?: 'male' | 'female' | 'other' | 'prefer_not_to_say'
          nationality?: string
          marital_status?: string
          address_line1?: string
          address_line2?: string
          city?: string
          state_province?: string
          postal_code?: string
          country?: string
          emergency_contacts?: any[]
          hire_date?: string
          probation_end_date?: string
          employment_status?: 'active' | 'inactive' | 'terminated' | 'on_leave' | 'suspended'
          employment_type?: 'full_time' | 'part_time' | 'contract' | 'intern' | 'consultant'
          work_location?: string
          allowed_work_locations?: string[]
          department_id?: string
          position_id?: string
          manager_employee_id?: string
          skip_level_manager?: string
          role_id?: number
          salary?: number
          salary_currency?: string
          salary_frequency?: string
          last_salary_review?: string
          next_salary_review?: string
          bonus_eligible?: boolean
          equity_eligible?: boolean
          pto_balance?: number
          sick_leave_balance?: number
          benefits_eligible?: boolean
          benefits_start_date?: string
          timezone?: string
          preferred_language?: string
          profile_photo_url?: string
          skills?: any[]
          certifications?: any[]
          languages?: any[]
          education?: any[]
          career_interests?: any[]
          development_goals?: any[]
          performance_rating?: number
          last_performance_review?: string
          next_performance_review?: string
          engagement_score?: number
          retention_risk?: string
          is_active?: boolean
          last_login?: string
          login_count?: number
          failed_login_attempts?: number
          account_locked?: boolean
          locked_until?: string
          two_factor_enabled?: boolean
          security_clearance?: string
          ai_insights?: any
          career_path_prediction?: any
          skill_recommendations?: any[]
          created_at?: string
          updated_at?: string
          created_by_id?: string
          updated_by_id?: string
          metadata?: any
          auth_user_id?: string
          manager_id?: string
          supervisor_id?: string
          created_by?: string
          updated_by?: string
        }
        Insert: Omit<Database['public']['Tables']['user_profiles']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['user_profiles']['Insert']>
      }
      departments: {
        Row: {
          id: string
          name: string
          code: string
          description?: string
          parent_department_id?: string
          manager_employee_id?: string
          budget?: number
          budget_currency?: string
          cost_center_code?: string
          location?: string
          timezone?: string
          working_hours?: any
          department_type?: string
          is_billable?: boolean
          is_revenue_generating?: boolean
          headcount_target?: number
          current_headcount?: number
          turnover_rate?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
          created_by_id?: string
          metadata?: any
        }
        Insert: Omit<Database['public']['Tables']['departments']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['departments']['Insert']>
      }
      positions: {
        Row: {
          id: string
          title: string
          code?: string
          description?: string
          department_id?: string
          reports_to_position_id?: string
          level?: string
          job_family?: string
          career_track?: string
          min_salary?: number
          max_salary?: number
          target_salary?: number
          currency?: string
          salary_review_frequency?: number
          responsibilities?: string[]
          requirements?: string[]
          preferred_qualifications?: string[]
          required_skills?: any[]
          preferred_skills?: any[]
          competency_matrix?: any
          performance_indicators?: any[]
          success_metrics?: any[]
          location_type?: string
          travel_requirement_percent?: number
          remote_work_eligible?: boolean
          is_leadership_role?: boolean
          direct_reports_max?: number
          headcount_approved?: number
          current_headcount?: number
          promotion_eligible_to?: any[]
          typical_tenure_months?: number
          is_active?: boolean
          effective_from?: string
          effective_to?: string
          created_at?: string
          updated_at?: string
          created_by_id?: string
          metadata?: any
        }
        Insert: Omit<Database['public']['Tables']['positions']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['positions']['Insert']>
      }
      roles: {
        Row: {
          id: number
          name: string
          display_name: string
          description?: string
          level: number
          parent_role_id?: number
          permissions_inheritance?: boolean
          is_system_role?: boolean
          color_code?: string
          icon?: string
          max_users?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
          created_by_id?: string
          metadata?: any
          permissions?: any
          company_id?: string
        }
        Insert: Omit<Database['public']['Tables']['roles']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['roles']['Insert']>
      }
      attendance_records: {
        Row: {
          id: string
          employee_id: string
          user_id?: string
          date: string
          shift_id?: string
          expected_start_time?: string
          expected_end_time?: string
          clock_in_time?: string
          clock_out_time?: string
          actual_start_work_time?: string
          actual_end_work_time?: string
          clock_in_location_id?: string
          clock_out_location_id?: string
          clock_in_latitude?: number
          clock_in_longitude?: number
          clock_out_latitude?: number
          clock_out_longitude?: number
          location_accuracy_meters?: number
          location_verified?: boolean
          gps_spoofing_detected?: boolean
          clock_in_photo_url?: string
          clock_out_photo_url?: string
          face_recognition_confidence?: number
          face_match_verified?: boolean
          photo_quality_score?: number
          total_hours?: number
          regular_hours?: number
          overtime_hours?: number
          break_duration_minutes?: number
          productive_hours?: number
          billable_hours?: number
          status?: 'present' | 'absent' | 'late' | 'half_day' | 'work_from_home' | 'on_leave'
          is_remote_work?: boolean
          is_sick_leave?: boolean
          is_authorized_absence?: boolean
          is_holiday?: boolean
          requires_attention?: boolean
          arrival_pattern?: string
          departure_pattern?: string
          break_pattern?: any[]
          productivity_score?: number
          engagement_indicators?: any
          weather_conditions?: any
          traffic_conditions?: string
          public_transport_delays?: boolean
          special_circumstances?: string
          device_info?: any
          app_version?: string
          network_type?: string
          battery_level?: number
          notes?: string
          employee_notes?: string
          manager_notes?: string
          approved_by_id?: string
          approved_at?: string
          review_required?: boolean
          correction_requested?: boolean
          anomaly_flags?: any[]
          risk_score?: number
          confidence_score?: number
          attendance_risk_score?: number
          pattern_analysis?: any
          behavioral_insights?: any
          recommendations?: any[]
          created_at?: string
          updated_at?: string
          metadata?: any
        }
        Insert: Omit<Database['public']['Tables']['attendance_records']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['attendance_records']['Insert']>
      }
      leave_requests: {
        Row: {
          id: string
          request_number?: string
          employee_id: string
          leave_type_id: string
          start_date: string
          end_date: string
          start_period?: string
          end_period?: string
          start_time?: string
          end_time?: string
          total_days: number
          business_days?: number
          total_hours?: number
          reason?: string
          detailed_reason?: string
          emergency_request?: boolean
          priority?: 'low' | 'medium' | 'high' | 'urgent'
          urgency_justification?: string
          contact_during_leave?: any
          emergency_contact_override?: any
          work_handover_completed?: boolean
          handover_notes?: string
          handover_checklist?: any[]
          coverage_arranged?: boolean
          coverage_details?: any
          status?: 'pending' | 'approved' | 'rejected' | 'cancelled' | 'withdrawn'
          sub_status?: string
          workflow_step?: number
          current_approver_id?: string
          escalation_level?: number
          auto_approved?: boolean
          requires_coverage?: boolean
          approval_chain?: any[]
          approvals_received?: any[]
          rejections_received?: any[]
          delegation_history?: any[]
          final_approver_id?: string
          approved_at?: string
          supporting_documents?: any[]
          medical_certificate_required?: boolean
          medical_certificate_submitted?: boolean
          medical_certificate_verified?: boolean
          medical_certificate_expiry?: string
          additional_documentation?: any[]
          team_impact_score?: number
          project_impact?: any[]
          client_impact_assessment?: string
          business_justification?: string
          cost_impact_estimate?: number
          revenue_impact_estimate?: number
          expected_return_date?: string
          actual_return_date?: string
          return_confirmed?: boolean
          return_to_work_interview?: boolean
          fitness_for_work_clearance?: boolean
          phased_return_plan?: any
          pay_impact?: any
          benefit_impacts?: any[]
          accrual_adjustments?: any
          pension_impact?: any
          statutory_leave_flag?: boolean
          fmla_covered?: boolean
          disability_related?: boolean
          workers_comp_claim?: string
          legal_requirements_met?: boolean
          approval_probability?: number
          similar_requests_analysis?: any
          pattern_analysis?: any
          risk_assessment?: any
          recommendation_engine?: any
          notification_preferences?: any
          reminder_schedule?: any[]
          communication_log?: any[]
          created_at?: string
          updated_at?: string
          submitted_at?: string
          metadata?: any
        }
        Insert: Omit<Database['public']['Tables']['leave_requests']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['leave_requests']['Insert']>
      }
      leave_types: {
        Row: {
          id: string
          name: string
          code: string
          description?: string
          category?: string
          max_days_per_year?: number
          max_days_per_period?: number
          accrual_method?: string
          accrual_rate?: number
          accrual_frequency?: string
          accrual_cap?: number
          proration_method?: string
          carry_forward_allowed?: boolean
          max_carry_forward_days?: number
          carry_forward_expiry_months?: number
          use_it_or_lose_it?: boolean
          cash_out_allowed?: boolean
          cash_out_rate?: number
          cash_out_threshold?: number
          min_notice_days?: number
          max_notice_days?: number
          min_duration_hours?: number
          max_duration_days?: number
          max_consecutive_days?: number
          min_gap_between_requests?: number
          blackout_periods?: any[]
          advance_booking_limit_days?: number
          requires_medical_certificate?: boolean
          medical_cert_threshold_days?: number
          requires_manager_approval?: boolean
          requires_hr_approval?: boolean
          requires_director_approval?: boolean
          auto_approve_threshold_days?: number
          delegation_allowed?: boolean
          is_paid?: boolean
          pay_rate_multiplier?: number
          affects_benefits?: boolean
          affects_seniority?: boolean
          affects_pension?: boolean
          affects_bonus_calculation?: boolean
          public_holiday_interaction?: string
          eligibility_rules?: any
          min_service_months?: number
          max_service_months?: number
          employment_types?: string[]
          applicable_countries?: string[]
          applicable_states?: string[]
          gender_specific?: boolean
          age_restrictions?: any
          statutory_leave?: boolean
          fmla_qualifying?: boolean
          workers_comp_related?: boolean
          disability_related?: boolean
          legal_requirements?: any
          reporting_requirements?: any
          weekend_counting?: string
          public_holiday_counting?: string
          half_day_allowed?: boolean
          hourly_leave_allowed?: boolean
          usage_patterns?: any
          approval_rates?: any
          seasonal_trends?: any
          cost_impact_analysis?: any
          color_code?: string
          icon?: string
          display_order?: number
          is_active?: boolean
          effective_from?: string
          effective_to?: string
          created_at?: string
          updated_at?: string
          created_by_id?: string
          metadata?: any
        }
        Insert: Omit<Database['public']['Tables']['leave_types']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['leave_types']['Insert']>
      }
      teams: {
        Row: {
          id: string
          name: string
          code?: string
          description?: string
          team_type?: string
          department_id?: string
          parent_team_id?: string
          team_lead_employee_id?: string
          max_members?: number
          current_members?: number
          target_members?: number
          budget?: number
          budget_currency?: string
          project_start_date?: string
          project_end_date?: string
          objectives?: string[]
          success_metrics?: any[]
          current_sprint?: any
          meeting_schedule?: any
          communication_channels?: any[]
          collaboration_tools?: any[]
          is_cross_functional?: boolean
          is_client_facing?: boolean
          requires_security_clearance?: boolean
          team_performance_score?: number
          velocity_points?: number
          team_satisfaction_score?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
          created_by_id?: string
          metadata?: any
        }
        Insert: Omit<Database['public']['Tables']['teams']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['teams']['Insert']>
      }
      companies: {
        Row: {
          id: string
          name: string
          code: string
          legal_name?: string
          tax_id?: string
          registration_number?: string
          industry?: string
          company_size?: string
          headquarters_address?: string
          city?: string
          country?: string
          phone?: string
          email?: string
          website?: string
          logo_url?: string
          timezone?: string
          currency?: string
          fiscal_year_start?: number
          working_days_per_week?: number
          working_hours_per_day?: number
          is_active?: boolean
          is_verified?: boolean
          settings?: any
          created_at?: string
          updated_at?: string
        }
        Insert: Omit<Database['public']['Tables']['companies']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['companies']['Insert']>
      }
      holidays: {
        Row: {
          id: string
          name: string
          date: string
          end_date?: string
          type?: string
          description?: string
          is_optional?: boolean
          is_partial_day?: boolean
          partial_hours?: number
          applicable_locations?: any[]
          applicable_departments?: any[]
          applicable_employment_types?: any[]
          applicable_roles?: any[]
          is_paid?: boolean
          pay_multiplier?: number
          work_required?: boolean
          overtime_eligible?: boolean
          observed_date?: string
          observance_rule?: string
          recurring?: boolean
          recurrence_pattern?: any
          cultural_significance?: string
          religious_observance?: boolean
          optional_for_non_observers?: boolean
          alternative_holidays?: any[]
          business_closure?: boolean
          essential_services_exempt?: boolean
          customer_impact_level?: string
          coverage_requirements?: any
          is_active?: boolean
          created_at?: string
          updated_at?: string
          created_by_id?: string
          metadata?: any
        }
        Insert: Omit<Database['public']['Tables']['holidays']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['holidays']['Insert']>
      }
    }
    Enums: {
      employment_status_type: 'active' | 'inactive' | 'terminated' | 'on_leave' | 'suspended'
      employment_type_enum: 'full_time' | 'part_time' | 'contract' | 'intern' | 'consultant'
      gender_type: 'male' | 'female' | 'other' | 'prefer_not_to_say'
      approval_status: 'pending' | 'approved' | 'rejected' | 'cancelled' | 'withdrawn'
      priority_level: 'low' | 'medium' | 'high' | 'urgent'
      attendance_status: 'present' | 'absent' | 'late' | 'half_day' | 'work_from_home' | 'on_leave'
    }
  }
}
